cmake_minimum_required(VERSION 3.25)
# Explicit target works on any host; no running code or browser installation.
if(JELY_ANGLE_PLATFORM STREQUAL "linux-x64")
  set(JELY_ARCHIVE_HASH a28d5ab638fa065853c80d5f27ea9d7ec7f8621d9242200f747798c5ed3193d4)
elseif(JELY_ANGLE_PLATFORM STREQUAL "linux-arm64")
  set(JELY_ARCHIVE_HASH d825d1f482493a66c537e313b5f126c61c3dfb785232d33716c74afdd18833de)
else()
  message(FATAL_ERROR "Specify -DJELY_ANGLE_PLATFORM=linux-x64 or linux-arm64. Windows uses bootstrap_angle.ps1; macOS ANGLE/Vulkan is not supported.")
endif()
set(JELY_DOWNLOAD_DIR "${CMAKE_CURRENT_LIST_DIR}/tools/downloads")
set(JELY_ASSET_DIR "${CMAKE_CURRENT_LIST_DIR}/vendor/angle/${JELY_ANGLE_PLATFORM}")
file(MAKE_DIRECTORY "${JELY_DOWNLOAD_DIR}" "${JELY_ASSET_DIR}")
set(JELY_ARCHIVE "${JELY_DOWNLOAD_DIR}/electron-v41.0.0-${JELY_ANGLE_PLATFORM}.zip")
if(EXISTS "${JELY_ARCHIVE}")
  file(SHA256 "${JELY_ARCHIVE}" JELY_EXISTING_HASH)
  if(NOT JELY_EXISTING_HASH STREQUAL JELY_ARCHIVE_HASH)
    message(FATAL_ERROR "Existing archive integrity mismatch. Preserve/inspect it before retrying: ${JELY_ARCHIVE}")
  endif()
else()
  file(DOWNLOAD "https://github.com/electron/electron/releases/download/v41.0.0/electron-v41.0.0-${JELY_ANGLE_PLATFORM}.zip" "${JELY_ARCHIVE}" EXPECTED_HASH "SHA256=${JELY_ARCHIVE_HASH}" TLS_VERIFY ON STATUS JELY_DOWNLOAD_STATUS)
  list(GET JELY_DOWNLOAD_STATUS 0 JELY_DOWNLOAD_CODE)
  if(NOT JELY_DOWNLOAD_CODE EQUAL 0)
    message(FATAL_ERROR "Download failed: ${JELY_DOWNLOAD_STATUS}")
  endif()
endif()
file(ARCHIVE_EXTRACT INPUT "${JELY_ARCHIVE}" DESTINATION "${JELY_ASSET_DIR}" PATTERNS libEGL.so libGLESv2.so libvulkan.so.1 LICENSES.chromium.html)
message(STATUS "Restored verified graphics-only runtime: ${JELY_ASSET_DIR}")
